### ISSUE TITLE
Please send me your email.

### ISSUE THREAD

**Issue by shdudwns** [ServerSoftwareArchiveTeam/Rocky#1]
I'll send you src.\
@Asuna-Yuuki

**Comment by Asuna-Yuuki** [comment]
@shdudwns wesleyvanneck1012@gmail.com

**Comment by shdudwns** [comment]
Please check it.
The version is an additional block and an additional version of the existing tessract
@Asuna-Yuuki

**Comment by shdudwns** [comment]
Is it a rocky project?
I thought it was a tessract.
The file I sent is tessract

**Comment by Asuna-Yuuki** [comment]
yes but the name is rocky

**Comment by Asuna-Yuuki** [comment]
Its still tessract based

**Comment by Asuna-Yuuki** [comment]
because of copyright

**Comment by shdudwns** [comment]
@Asuna-Yuuki  okay

**Comment by Asuna-Yuuki** [comment]
i change the name to ServerSoftwareArchiveTeam

**Comment by shdudwns** [comment]
@Asuna-Yuuki okay

**Comment by shdudwns** [comment]
Shouldn't we invite the developer?
Since I am a beginner, I am not much of a ...
@Asuna-Yuuki

**Comment by Asuna-Yuuki** [comment]
uhh @shdudwns idk if whants dat he is a dick to me always
